### ISSUE TITLE
pip install -e ifp-sample error

### ISSUE THREAD

**Issue by THHHomas** [jackd/ifp-sample#1]
ERROR: ifp-sample is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).

**Comment by jackd-msft** [comment]
Are you running from the same directory from which you cloned? If you `cd` into the `ifp-sample` directory then it would be `pip install -e .`

Also, I've stopped working on this because I found `numba` way easier to work with and gave better results. You may find similar/faster functionality [here](https://github.com/jackd/numba-neighbors) (it's mostly KDTree stuff, but there's some IFP in there too).

**Comment by jackd** [comment]
Hoping this is resolved. Feel free to post back if not.
