### ISSUE TITLE
Why K=8?

### ISSUE THREAD

**Issue by WhatAShot** [jackd/ifp-sample#2]
Nice job.
You set k=8 in the example at the bottom of README. 
I don't know why k=8 and if k!=8, what will happen?
Thank you very much.

**Comment by jackd-msft** [comment]
Eh, had to pick a number. The use-case I wrote this for typically used 8-32.

Note I've since stopped work on this repo because I found `numba` to be way nicer. Feel free to experiment with it [numba-neighbors](https://github.com/jackd/numba-neighbors). The documentation is probably a bit lack-luster, but hopefully [this example](https://github.com/jackd/numba-neighbors/blob/master/example/ifp_sample.py) and a bit of digging through source code is enough to get your through.

**Comment by WhatAShot** [comment]
Thank you. Both repos are good.
